name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.0.3
  EXPORT_NAME: Royal_Cupcakes

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-4.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export-release --headless "Windows Desktop" build/windows/$EXPORT_NAME.exe
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: royal_cupcakes_build
          release_name: Royal Cupcakes Latest Build
          draft: false
          prerelease: false
      
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/windows
          asset_name: royal-cupcakes.zip
          asset_content_type: application/zip
